var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                   xx      xx      x!!!x        ",
   "                                    o o      xx                    x!!!x        ",
   "                                                                   x!!!x        ",
   "                                   xxxxx                   tt       xvx         ",
   "                                                         tttttt             xx  ",
   "  xx                                      o o           tttttttt             x  ",
   "  x                     o                                ttwwtt              x  ",
   "  x                                      xxxxx             ww              o x  ",
   "  x          xxxx       o                                  ww                x  ",
   "  x  @       x  x                                          ww      xxxxx     x  ",
   "  xxxxxxxxxxxx  xxxxxxxxxxxxxxx   xxxxxxxx     xxxxxxx     xxxxxxxxx    xxxxxxx ",
   "                              x   x      x     x     x     x                    ",
   "                              x!!!x      x!!!!!x     x!!!!!x                    ",
   "                              x!!!x      x!!!!!x     x!!!!!x                    ",
   "                              xxxxx      xxxxxxx     xxxxxxx                    ",
   "                                                                                ",
   "                                      xxxx                                      "],
  ["                                      x!!x                                                                   x!x  ",
   "                                      x!!x                                                                   x!x  ",
   "                                      x!!xxxxxxxxxx                xxxxxxxxx                                 x!x  ",
   "                                      xx!!!!!!!!!!xx xxxxxxxxx                                               x!x  ",
   "                                      xx!!!!!!!!!!xx        xxxx                                             x!x  ",
   "                                       xxxxxxxxxx!!x                             xxxxxx         o   o   o    x!x  ",
   "                                               xx!xx              o      o                                  xx!x  ",
   "                                                x!x                                       xxxxxxxxxxxxxxxxxxx!!x  ",
   "                                                xvx              xx     xx                !!!!!!!!!!!!!!!!!!!!xx  ",
   "                                                             xxx     |      xxx           xxxxxxxxxxxxxxxxxxxxx   ",
   "                                                              xx!!!!!!!!!!!xx            v                        ",
   "                                                               xxxx!!!!!xxxx                                      ",
   "                                            x                     xxxxxxx        xxx         xxx                  ",
   "                                            x      xxx                           x x         x x                  ",
   "                                            x        x                             x         x                    ",
   "                 tttt                       x        x                             xx        x                    ",
   "                tttttt                      xxx      x                             x         x                    ",
   "                 twwt                       x        x     o    o    x     x         x        xx                  ",
   "                  ww          xxx   xxx     x        x               x     xxxxxxxxxxxxx       x                  ",
   "                  ww            x   x       x        x    xxxxxxxx   x     x                   x                  ",
   "             xxxxxxxxxxx        x o x       x      xxx               x                         x                  ",
   "     @       x         x        x   x       x        x               x                       xx                   ",
   "    xxx      x         x        x   x       x        x               x     o      xxxxxx      x                   ",
   "    x x      x         x       xx o xx      x        x               x     =     x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!!xx     xx!!!!!xx       x!!!!!!!!!!     x           x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxx     x!!!!!!!xx!     xxxxxxxxxxxxx xx  o o  xx                    ",
   "!!!!x x!!!!!!x         x!!!!!x    o                 xx!!!!!!xx !                    xx     xx                     ",
   "!!!!x x!!!!!!x         x!!!!!x                      xx!!!!!xx  !                     xxxxxxx                      ",
   "!!!!x x!!!!!!x         x!!!!!x                     xx!!!!!xx   !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!x                     xx!!!!!xx   !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!xx          xxxxxxxxxxx!!!!!!xx   !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxxxxx!!!!!!!!!!!!!!!xx    !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                  "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                           xxx                                ",
   "                                        o                                                                     ",
   "                                                               x       x        o                             ",
   "                                        t                      x  ooo  x       xxx                            ",
   "                                       ttt                     x       x      x!!!x                           ",
   "                                      ttttt                    xxxxxxxxx       xxx                            ",
   "                                     ttttttt        xxxxx                                                     ",
   "                                       www            xx                                                      ",
   "                                       www            x                                                       ",
   "                                       www            x                                xxxxxxx                ",
   "                                    wwwwwwwwwww       x                                                       ",
   "                                       www =          x            xxx                                        ",
   "                                       www            x                                                       ",
   "                                       www         =  x     o                xxx                              ",
   "                                 wwwwwwwwww           x                     x!!!x        o                    ",
   "                                       www            x    xxxxxx              v        xxx                   ",
   "                                       www            x              x                 x!!!x                  ",
   "                                       www       o o  x!!!!!!!!!!!!!!x                  xvx                   ",
   "                             xxxxxxxxxxxxxxx          x!!!!!!!!!!!!!!x                           xxx          ",
   "                             x             x   xxxxxxxxxxxxxxxxxxxxxxxxxx                                    ",
   "                             xx           xx                                                                  ",
   "  xxx                         x     x     x                                                              xxx  ",
   "  x x                  xxxx   x    xxx    x                                                 xxxx         x x  ",
   "  x                           x    xxx    xxxxx                          xxxxx                             x  ",
   "  x                                       x                              x   x                             x  ",
   "  x                 o                     x                              x x x                   o         x  ",
   "  x                 t                     x       |xxxx     |xxxx|     xxx xxx      o            tt        x  ",
   "  x                ttt             o o    x                              x         xxx          tttt       x  ",
   "  x               ttttt       xx          x                             xxx       x!!!x        tttttt      x  ",
   "  x               o w o       x!!! xxx !!!x  x    x    x    x    x      x x        xxx          twwt       x  ",
   "  x                 w        xxxxxxxxxxxxx  x oo x    x oo x    x oo  xx xx                      ww        x  ",
   "  x      @          w         x           x!!x    x!!!!x    x!!!!x    xx   xx                    ww        x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "         x                                                                                                    ",
   "        xxx                                                                                                   ",
   "       xxxxx                                                                                                  ",
   "        xxx                                                            x                                      ",
   "         x                 xx  xx     xxxx     xx    xx               xxx                                     ",
   "                           xx  xx   xx    xx   xx    xx              xxxxx                                    ",
   "                            xxxx    xx    xx   xx    xx               xxx                                     ",
   "                             xx     xx    xx   xx    xx                x                                      ",
   "                             xx     xx    xx   xx    xx                                                       ",
   "   x                         xx       xxxx      xxxxxx                                                        ",
   "  xxx                                                                                                         ",
   " xxxxx                                                                                x                       ",
   "  xxx               xx      xx   xxxxxxxx   xx        xx   xxx                       xxx                      ",
   "   x                xx      xx      xx      xxxx      xx   xxx                      xxxxx                     ",
   "                    xx  xx  xx      xx      xx  xx    xx   xxx                       xxx                      ",
   "                    xx  xx  xx      xx      xx    xx  xx   xxx                        x                       ",
   "                    xx  xx  xx      xx      xx      xxxx                                                      ",
   "                     xxx  xxx    xxxxxxxx   xx        xx    x                                                 ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "             x                                                                                                ",
   "            xxx                                                      x                                        ",
   "           xxxxx                                                    xxx                                       ",
   "            xxx                                                    xxxxx                                      ",
   "             x                                                      xxx                                       ",
   "                                                                     x                                        ",
   "                                                                                                              ",
   "     @                                                                                                        ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              ",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
